yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.index, name='main_page'),
    path('group/<slug:slug>/', views.group_posts, name='group_posts_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns = [
#         path('__debug__/', include(debug_toolbar.urls)),
#     ] + urlpatterns

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

from core.models import CreatedModel


User = get_user_model()


class Post(CreatedModel):

    text = models.TextField(
        verbose_name='текст:',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
    )
    group = models.ForeignKey(
        'Group',
        blank=True,
        null=True,
        related_name='posts',
        on_delete=models.PROTECT,
        verbose_name='группа:',
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True,
    )

    def __str__(self):
        return self.text[:15]


class Group(models.Model):

    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=255, unique=True, db_index=True,
                            verbose_name="URL")
    description = models.TextField()

    def __str__(self) -> str:
        return self.title


class Comment(CreatedModel):

    post = models.ForeignKey(
        Post,
        related_name='comments',
        on_delete=models.CASCADE,
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
    )
    text = models.TextField(
        verbose_name='картинка',
    )

    def __str__(self):
        return self.text


class Follow(CreatedModel):

    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following'
    )

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('group', 'text', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text', )

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page

from .forms import PostForm, CommentForm
from .models import Follow, Group, Post, User
from .utils.paginator import paginator


@cache_page(20, key_prefix='index_page')
def index(request):
    template = 'posts/index.html'
    post_list = Post.objects.select_related('group')
    page_obj = paginator(post_list, request)
    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


def group_posts(request, slug):
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.select_related('group')
    page_obj = paginator(posts, request)
    context = {
        'group': group,
        'page_obj': page_obj
    }
    return render(request, template, context)


def profile(request, username):
    template = 'posts/profile.html'
    author = get_object_or_404(User, username=username)
    post_list_user = author.posts.select_related('author').filter(
        author__username=username
    )
    count_post = post_list_user.count()
    page_obj = paginator(post_list_user, request)
    following = request.user.is_authenticated and Follow.objects.filter(
        user=request.user,
        author=author
    ).exists()
    context = {
        'page_obj': page_obj,
        'author': author,
        'count_post': count_post,
        'following': following,
    }
    return render(request, template, context)


def post_detail(request, post_id):
    template = 'posts/post_detail.html'
    post = get_object_or_404(Post, pk=post_id)
    count_post = Post.objects.select_related('post').filter(
        author_id=post.author.id
    ).count()
    form = CommentForm()
    comments = post.comments.select_related('post')
    context = {
        'post': post,
        'count_post': count_post,
        'form': form,
        'comments': comments,
    }
    return render(request, template, context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None, files=request.FILES or None)
    template = 'posts/post_create.html'

    if not form.is_valid():
        return render(request, template, {'form': form})

    post = form.save(commit=False)
    post.author = request.user
    post.save()
    return redirect('posts:profile', post.author)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    template = 'posts/post_create.html'
    form = PostForm(instance=post)

    if request.method == 'POST':
        form = PostForm(
            request.POST,
            files=request.FILES or None,
            instance=post
        )
        if form.is_valid():
            form.save()
        return redirect('posts:post_detail', post_id=post_id)

    context = {
        'form': form,
        'post': post,
        'is_edit': True
    }

    return render(request, template, context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    template = 'posts/follow.html'
    post_list = Post.objects.all().filter(author__following__user=request.user)
    page_obj = paginator(post_list, request)
    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if request.user != author:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(user=request.user, author=author).delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/follow.html
{% extends "base.html" %}
{% load thumbnail %}

{% block title %}
 Посты избранных авторов
{% endblock %}

{% block content %}
  <h1>Посты избранных авторов:</h1>
  {% include 'posts/includes/switcher.html' %}
  {% for post in page_obj %}
  {% include "posts/includes/post_list.html" %}
    {% if post.group %}
      <a href="{% url 'posts:group_posts_list' post.group.slug %}">
        все записи группы
      </a>
    {% endif %}

    {% if not forloop.last %}
      <hr>
    {% endif %}
  {% endfor %} 
  {% include "posts/includes/paginator.html" %}

{% endblock  %}

yatube/templates/posts/group_list.html
{% extends "base.html" %}
{% load thumbnail %}

{% block title %}
 {{ group.title }}
{% endblock %}
{% block header %}<h1>{{ group.title }}</h1>{% endblock %}
{% block content %}
<h1>{{ group.title }}</h1>
<p>
  {{ group.description }}
</p>
  {% for post in page_obj %}
   {% include 'posts/includes/group_list.html' %}    
    {% if not forloop.last %}
      <hr>
    {% endif %}
  {% endfor %} 
  {% include "posts/includes/paginator.html" %}
{% endblock  %}

yatube/templates/posts/index.html
{% extends "base.html" %}
{% load thumbnail %}

{% block title %}
  Последние обновления на сайте
{% endblock %}

{% block content %}
  <h1>Последние обновления на сайте</h1>
  {% include 'posts/includes/switcher.html' %}
  {% for post in page_obj %}
  {% include "posts/includes/post_list.html" %}
    {% if post.group %}
      <a href="{% url 'posts:group_posts_list' post.group.slug %}">
        все записи группы
      </a>
    {% endif %}

    {% if not forloop.last %}
      <hr>
    {% endif %}
  {% endfor %} 
  {% include "posts/includes/paginator.html" %}

{% endblock  %}

yatube/templates/posts/post_create.html
{% extends "base.html" %}

  {% block title %}
    {% if is_edit %}
      Редактировать запись
    {% else %}
      Добавить запись
    {% endif %}
  {% endblock %}

  {% block content %}
  {% load user_filters %}
    <div class="container py-5">
      <div class="row justify-content-center">
        <div class="col-md-8 p-5">
          <div class="card">
            <div class="card-header">       
              Новый пост             
              {% if form.errors %}
                {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endif %}
              <form method="post" enctype="multipart/form-data" action="{% if is_edit %}
              {% url 'posts:post_edit' post.id %}
               {% else %}
              {% url 'posts:post_create' %}
              {% endif %}">
              {% csrf_token %}
              {% for field in form %}
                <div class="form-group row my-3 p-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                    {% if field.field.required %}
                      <span class="required text-danger">*</span>
                    {% endif %}
                  </label>    
                  {{ field|addclass:"form-control" }}
                  {% if field.help_text %}
                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                      {{ field.help_text|safe }}
                    </small>
                  {% endif %}
                </div>
              {% endfor %}
                <div class="col-md-6 offset-md-4">
                  <button type="submit" class="btn btn-primary">
                    {% if is_edit %}
                      Сохранить
                    {% else %}
                      Добавить
                    {% endif %}               
                  </button> 
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% load thumbnail %}

{% block title %}
{{ post.text|slice:":30" }}
{% endblock %}

{% block content %}
    <main>
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
            {% if post.group %}
            <li class="list-group-item">
              Группа: <b>{{ post.group.title }}</b>
            </li>
            <li class="list-group-item">
                <a href="{% url 'posts:group_posts_list' post.group.slug %}">
                все записи группы
              </a>
            </li>
            {% endif %}
            <li class="list-group-item">
              Автор: <b>{{ post.author.get_full_name }}</b>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:{{ count_post }}
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author %}">
                все посты пользователя
              </a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}

          <p>
            {{ post.text }}
          </p>
          {% if user == post.author %}
          <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
            Редактировать
          </a>
          {% endif %}

        {% load user_filters %}

        {% if user.is_authenticated %}
          <div class="card my-4">
            <h5 class="card-header">Добавить комментарий:</h5>
            <div class="card-body">
              <form method="post" action="{% url 'posts:add_comment' post.id %}">
                {% csrf_token %}      
                <div class="form-group mb-2">
                  {{ form.text|addclass:"form-control" }}
                </div>
                <button type="submit" class="btn btn-primary">Отправить</button>
              </form>
            </div>
          </div>
        {% endif %}

        {% for comment in comments %}
          <div class="media mb-4">
            <div class="media-body">
              <h5 class="mt-0">
                <a href="{% url 'posts:profile' comment.author.username %}">
                  {{ comment.author.username }}
                </a>
              </h5>
              <p>
                {{ comment.text }}
              </p>
            </div>
          </div>
        {% endfor %} 
      </article>
      </div> 
    </main>
  </body>
</html>
{% endblock %}

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% load thumbnail %}

{% block title %}
  Профайл пользователя {{ user }}
{% endblock %}
{% block content %}
  <div class="mb-5">
    <h1>Все посты пользователя {{ author.get_full_name }}</h1>
    <h3>Всего постов: {{ count_post }}</h3>
    {% if following %}
      <a
        class="btn btn-lg btn-light"
        href="{% url 'posts:profile_unfollow' author.username %}" role="button"
      >
        Отписаться
      </a>
    {% else %}
        <a
          class="btn btn-lg btn-primary"
          href="{% url 'posts:profile_follow' author.username %}" role="button"
        >
          Подписаться
        </a>
     {% endif %}
  </div>
  {% for post in page_obj %}
    {% include 'posts/includes/profile_list.html' %}
      {% if post.group %}
      <li>  
      <a href="{% url 'posts:group_posts_list' post.group.slug %}">
        все записи группы
      </a>
    </li>
    {% endif %}
    </li> 
    {% if not forloop.last %}
      <hr>
    {% endif %}
  {% endfor %} 
  {% include "posts/includes/paginator.html" %}
{% endblock  %}